name: CI

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  build:
    timeout-minutes: 7
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        ref: 'master'
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: npm install
    - uses: softprops/turnstyle@v1
      with:
        poll-interval-seconds: 25
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: DEV deployment
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
      run: ./deploy.js dev 518f6460-1f14-4d4e-8b23-cc5871634f80

    - name: PROD deployment
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
      run: ./deploy.js prod fb1e2de7-e6df-4989-946b-0fe45ba2d971